### ISSUE TITLE
Not work with snippet code

### ISSUE THREAD

**Issue by ulmzr** [AlexxNB/vscode-malinajs-highlight#1]
Hi, Alex.
I cant using snippet or emmet. I have to manually type start end closing tags. 
Please, make it work like regular html extension.
Regards,

**Comment by AlexxNB** [comment]
It was my first experience with VS Code plugin. It is just highlighter there no any logic for things you want. Sure using language server for more complex Malina.js support will be better, but it is not my level now. Maybe some help? =)

**Comment by ulmzr** [comment]
Ok, Alexx.
I've added settings.json in vscode, like this [help](https://stackoverflow.com/questions/56311467/configure-emmet-for-jsx-in-vscode/56472703#comment111033969_56472703);
```json
{
   "emmet.includeLanguages": {
      "malinajs": "html"
   },
}
```
Seem like its working know.
Thanks Alexx

**Comment by AlexxNB** [comment]
Cool, thank you for the answer! Will help others.
